# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: aws-runner
    cloud: aws
    instance_type: t3a.2xlarge
    # Custom Ubuntu 18.04 image
    machine_image: ami-0febc229056b2de48
    workflow: .github/workflows/run_tests.yml
